name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: tor-hidden-service:test
    - name: Test Docker image
      run: |
        docker run --name tor-test -d tor-hidden-service:test
        sleep 5
        docker logs tor-test
        docker stop tor-test
        docker rm tor-test
    
  security-scan:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        load: true
        tags: tor-hidden-service:test
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'tor-hidden-service:test'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        severity: 'CRITICAL,HIGH'
    
  publish:
    runs-on: ubuntu-latest
    needs: [build, security-scan]
    if: github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Extract Tor version
      id: tor_version
      run: |
        TOR_VERSION=$(grep -oP 'TOR_VERSION=\K[^"]+' Dockerfile)
        echo "TOR_VERSION=$TOR_VERSION" >> $GITHUB_ENV
        echo "tor_version=$TOR_VERSION" >> $GITHUB_OUTPUT
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/tor-hidden-service:latest
          ghcr.io/${{ github.repository_owner }}/tor-hidden-service:${{ github.sha }}
          ghcr.io/${{ github.repository_owner }}/tor-hidden-service:tor-${{ env.TOR_VERSION }}
